remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-them
title: Today I Learn
color_scheme: light
search_enabled: false
footer_content: "Copyright &copy; 2023 Luong Vu"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
